version: "2"

output:
  sort-order:
    - file
    - linter
  show-stats: true

linters:
  default: all
  disable:
    - gochecknoglobals
    - wrapcheck
    - depguard
    - exhaustruct
    - gochecknoinits
    - godox
    - mnd
    - err113
    - ireturn
    - gomoddirectives
    - tagliatelle
  
  settings:
    cyclop:
      max-complexity: 15
    gosec:
      excludes:
        - G204
        - G306
    varnamelen:
      max-distance: 10
      ignore-names:
        - ok
        - wf
        - ch
        - i
        - fn
      ignore-decls:
        - r interface{}
    perfsprint:
      strconcat: false
    nestif:
      min-complexity: 7
    funlen:
      ignore-comments: true
      lines: 65
    govet:
      enable:
        - shadow
  
  exclusions:
    paths:
      - ".*_test\\.go"
      - "fake_.*\\.go"
      - "fake/"
    generated: strict

formatters:
  default: all
  disable:
    - gci
    - gofumpt
