apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build

on:
  workflow_dispatch:
  push:
    branches:
    - '**'

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

jobs:
  build:
    steps:
    - id: checkout
      name: Get source code
      uses: cloudbees-io/checkout@v1

    - id: build-image
      name: Build, scan and push to ECR
      if: ${{ vars.workflow_execution_env == 'production' }}
      uses: calculi-corp/cb-internal-shared-actions/build/action@v8
      with:
        go-binary-build: "true"
        go-build-ldflags: "-X main.version=${{ cloudbees.version }}"
        go-build-main: "./cmd/registry-config"
        go-binary-name: "registry-config"
        kaniko-build: "true"
        run-unit-test: "true"
        golangci-lint: "true"
        registry-url: 020229604682.dkr.ecr.us-east-1.amazonaws.com
        registry-image-name: actions/registry-config
        registry-type: ECR
        oidc-iam-role: ${{ vars.oidc_staging_iam_role }}

  create-upgrade-pr:
    needs:
      - build
    if: ${{ cloudbees.scm.branch == 'main' }}
    steps:
      - uses: calculi-corp/platform-helmfiles/actions/set-component-version@main
        with:
          component: registry-config
          artifact-key: public.actions.registry-config
          artifact-value: ${{ cloudbees.scm.sha }}
          app-id: ${{ vars.platform_helmfiles_app_id }}
          installation-id: ${{ vars.platform_helmfiles_installation_id }}
          private-key-b64: ${{ secrets.platform_helmfiles_gh_app_key_b64 }}